services:
  - type: web
    name: social-publisher
    env: python
    plan: free
    region: frankfurt
    buildCommand: ""
    startCommand: python server.py
    rootDir: social-publisher
    autoDeploy: true
